### PR TITLE
Pixi v4

### PR DESCRIPTION
**Pull request by yanshcherbakovatredspace**
I figured that I would start this pull request now as I will pulling in commit from the pixi dev branch as commits are made, to track that the changes made in Springroll stay intact and test the branch in the meantime.

The merge will of course happen when Pixi v4 is released.

### CODE REVIEW

**Comment by yanshcherbakovatredspace** [comment]
@bigtimebuddy @andrewstart Please review if any of the springroll specific items have been affected.

Since Pixi v4 launched, we can merge this into master?

**Comment by andrewstart** [comment]
The 5 `stage___` events should be removed, as Pixi now has events on the InteractionManager. This does mean that SpringRoll will have to change to listen for `mousedown` and `touchstart` instead of `stagedown`, etc.

**Comment by andrewstart** [comment]
Other than the events that I mentioned, it looks like everything was merged nicely.

**Comment by yanshcherbakovatredspace** [comment]
@andrewstart Just a thought, wouldn't we want to keep the `stage__` events for the sake of backwards compatibility. As the game developer will have to change the events if they choose to upgrade to this version with an existing game that uses the stage events.

**Pull request closed without merging**
